definitions:
  controllers.CartInput:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  controllers.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.OrderInput:
    properties:
      cart_id:
        type: integer
      user_id:
        type: integer
    required:
    - cart_id
    - user_id
    type: object
  controllers.ProductInput:
    properties:
      categories:
        items:
          type: string
        type: array
      count:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: integer
      store_id:
        type: integer
    required:
    - categories
    - count
    - image_url
    - name
    - price
    - store_id
    type: object
  controllers.RegisterInput:
    properties:
      address:
        type: string
      email:
        type: string
      password:
        type: string
      role:
        enum:
        - USER
        - MERCHANT
        type: string
      username:
        type: string
    required:
    - address
    - email
    - password
    - role
    - username
    type: object
  controllers.StoreInput:
    properties:
      address:
        type: string
      description:
        type: string
      name:
        type: string
    required:
    - address
    - description
    - name
    type: object
  controllers.changePasswordInput:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  controllers.updateUser:
    properties:
      address:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /Stores:
    get:
      description: registering a user from public access.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: get stores, anyone can use this
      tags:
      - Store
  /carts:
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to create a Cart
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.CartInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Create Cart, user role must be USER
      tags:
      - Cart
  /carts/:cart_id/items/:item_id:
    delete:
      description: registering a user from public access.
      parameters:
      - description: the body to create a cart item
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.CartInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: delete cart item, user role must be USER
      tags:
      - Cart
  /carts/:id/items:
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to create a cart item
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.CartInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: add cart item, user role must be USER
      tags:
      - Cart
  /orders:
    get:
      description: registering a user from public access.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: get Orders, anyone can use this
      tags:
      - Order
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to create a Order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.OrderInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Create Order, user role must be USER
      tags:
      - Order
  /orders/:id:
    delete:
      description: registering a user from public access.
      parameters:
      - description: the body to delete a Order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.OrderInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: delete Order, user role must be MERCHANT
      tags:
      - Order
  /orders/:id/cancel:
    put:
      description: registering a user from public access.
      parameters:
      - description: the body to delete a Order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.OrderInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: cancel Order, user role must be MERCHANT
      tags:
      - Order
  /orders/:id/pay:
    put:
      description: registering a user from public access.
      parameters:
      - description: the body to delete a Order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.OrderInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: cancel Order, user role must be MERCHANT
      tags:
      - Order
  /products:
    delete:
      description: registering a user from public access.
      parameters:
      - description: the body to delete a Product
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ProductInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: delete product, user role must be MERCHANT
      tags:
      - Product
    get:
      description: registering a user from public access.
      parameters:
      - description: the body to create a Product
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ProductInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Create Product, user role must be MERCHANT
      tags:
      - Product
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to create a Product
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ProductInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Create Product, user role must be MERCHANT
      tags:
      - Product
    put:
      description: registering a user from public access.
      parameters:
      - description: the body to update a Product
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.ProductInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Update Product, user role must be MERCHANT
      tags:
      - Product
  /stores:
    delete:
      description: registering a user from public access.
      parameters:
      - description: the body to delete a Store
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.StoreInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: delete Store, user role must be MERCHANT
      tags:
      - Store
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to create a Store
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.StoreInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Create Store, user role must be MERCHANT
      tags:
      - Store
    put:
      description: registering a user from public access.
      parameters:
      - description: the body to update a Store
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.StoreInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: Update Store, user role must be MERCHANT
      tags:
      - Store
  /users:
    get:
      description: get user
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: get user
      tags:
      - User
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register a user.
      tags:
      - User
  /users/:
    put:
      description: update user info
      parameters:
      - description: the body to update a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.updateUser'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: update user info
      tags:
      - User
  /users/login:
    post:
      description: Logging in to get jwt token to access api by user's role.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login as as user.
      tags:
      - User
  /users/password:
    put:
      description: change user's password
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.changePasswordInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerToken: []
      summary: change user's password
      tags:
      - User
swagger: "2.0"
